### PR TITLE
Remove unused arguments when calling testbed_config_vchassis playbook.

### LINKED ISSUE #17922: Regression: `add-topo` fails `testbed_config_vchassis.yml` with `ERROR! Specified hosts and/or --limit does not match any hosts`
### Is it platform specific

generic

### Importance or Severity

High

### Previous Working Version

Introduced by https://github.com/sonic-net/sonic-mgmt/pull/17647

### Steps to Reproduce

In https://github.com/sonic-net/sonic-mgmt/pull/17647 `add-topo` was updated with a new ansible playbook call on T2 topologies:
```
    if [[ $topo == *"t2"* ]]; then
      ansible-playbook -i ${inv_name} testbed_config_vchassis.yml --vault-password-file="$passfile" -l "$duts" -e testbed_name="$testbed_name" \
      -e topo="$topo" -e testbed_file=$tbfile -e vm_file=$vmfile  -e server="$server" $@
    fi
```

This playbook fails with:
```
ansible-playbook 2.8.20
  config file = /data/ansible/ansible.cfg
  configured module search path = [u'/data/ansible/library', u'/data/ansible/library/ixia']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.18 (default, Dec  9 2024, 19:35:20) [GCC 9.4.0]
Using /data/ansible/ansible.cfg as config file
host_list declined parsing /data/ansible/lab as it did not pass it's verify_file() method
script declined parsing /data/ansible/lab as it did not pass it's verify_file() method
auto declined parsing /data/ansible/lab as it did not pass it's verify_file() method
Parsed /data/ansible/lab inventory source with ini plugin
[WARNING]: Could not match supplied host pattern, ignoring: server_1
ERROR! Specified hosts and/or --limit does not match any hosts
```

I think the problem may be that only the `-i ${inv_name}` inventory file is included and not `-i $vmfile`.
At least on our setup it seems like `server_1` is defined in the `$vmfile` and not `${inv_name}`.

### Impact of this regression

`add-topo` stage fails, can't setup sonic-mgmt infra.

### Relevant log output

```shell

```

### Output of `show version`

```shell

```

### Attach files (if any)

_No response_

### PR DESCRIPTION
**Pull request by BYGX-wcr**
### Description of PR

Summary: Previously, the testbed_config_vchassis.yml playbook was called with some unnecessary arguments which may cause failures for certain users depending on the user input. Now, we remove the unnecessary arguments to reduce the possibility caused by misinput.
Fixes #17922  (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411

### CODE REVIEW

File: ansible/testbed-cli.sh [hunk 1]
```diff
@@ -332,8 +332,7 @@ function add_topo
     fi
 
     if [[ $topo == *"t2"* ]]; then
-      ansible-playbook -i ${inv_name} testbed_config_vchassis.yml --vault-password-file="$passfile" -l "$duts" -e testbed_name="$testbed_name" \
-      -e topo="$topo" -e testbed_file=$tbfile -e vm_file=$vmfile  -e server="$server" $@
+      ansible-playbook -i ${inv_name} testbed_config_vchassis.yml --vault-password-file="$passfile" -l "$duts" -e topo="$topo"
```
Comment (arista-nwolfe) [inline ansible/testbed-cli.sh:335]: I think the password file is saved in the variable `${passwd}` in `add_topo`, not sure how important this is for this call.

**Review by arista-nwolfe — APPROVED** [review]

**Comment by BYGX-wcr** [comment]
@rlhui , @arlakshm, can you merge this PR?

**Review by rlhui — APPROVED** [review]
